name = input("请输入你的名字： ")
age = int(input("请输入你的年龄： "))
weight = float(input("请输入你的体重： "))
stu_id = int(input("请输入你的学号： "))
print("你的名字是%s" %name)
print("你的年龄是%d" %age)
print("你的年龄是%.2f" %weight)
print("你的学号是%03d" %stu_id)
print("你的名字是%s,你的年龄是%d" %(name,age))